### ISSUE TITLE
Enlaces en nueva pestaña

### ISSUE THREAD

**Issue by n1nj4t4nuk1** [mpardalm/mpardalm.github.io#1]
Como propuesta, creo que estaría bien que los enlaces (como el de twitter, insta etc.) se abrieran en una nueva pestaña.
Por ejemplo en el caso del enlace a twitter:
`<a href="http://twitter.com/migue_pardal" target="_blank">@migue_pardal</a>`

**Comment by mpardalm** [comment]
Gracias por el aporte, queda mucho mejor.
